FROM python

WORKDIR /src

COPY ./etc/docker/wordpress/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./etc/docker/wordpress/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

COPY ./wp-theme /lhp

ENTRYPOINT ["/entrypoint"]
